name: .NET

on:
  push:
    tags: 
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+-preview'
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Set MINVERBUILDMETADATA
      run: echo MINVERBUILDMETADATA=$(git rev-parse --short ${GITHUB_SHA})  >> $GITHUB_ENV
      shell: bash
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test 
    - name: Package templates
      run: dotnet pack --configuration Release -p:RepositoryUrl=https://github.com/${{ github.repository }}.git 
      working-directory: source/dotnettemplates
    - name: Publish Github Packages
      if: ${{ github.event_name == 'push' }}
      run: |
           for nupkg in $(find . -name *.nupkg)
           do
            echo Pushing $nupkg
            dotnet nuget push $nupkg --api-key ${{ secrets.GHPACKAGES_PAT }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate
           done
      shell: bash
    - name: Publish Nuget Packages
      if: startsWith( github.ref, 'refs/tags/' )
      run: |
           for nupkg in $(find . -name *.nupkg)
           do
            echo Pushing $nupkg
            dotnet nuget push $nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
           done
      shell: bash
    - name: Build Changelog
      if: startsWith( github.ref, 'refs/tags/' )
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      if: startsWith( github.ref, 'refs/tags/' )    
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: ${{steps.github_release.outputs.changelog}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
